name: "Build"
description: "Build and publish Docker image"
inputs:
  docker-user:
    description: "Docker User"
    required: true
  docker-password:
    description: "Docker Password"
    required: true
  docker-image-name:
    description: "Docker Image Name"
    required: true
  working-directory:
    description: "Optional working directory"
    required: false
    default: ./
runs:
  using: "composite"
  steps:
    - id: docker-login
      run: echo ${{ inputs.docker-password }} | docker login https://ghcr.io --username ${{ inputs.docker-user }} --password-stdin
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: docker-build
      run: docker build -t ghcr.io/${{ github.repository }}/${{ inputs.docker-image-name }}:latest .
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: docker-push
      run: docker push ghcr.io/${{ github.repository }}/${{ inputs.docker-image-name }}:latest
      shell: bash
      working-directory: ${{ inputs.working-directory }}
