name: "Deploy"
description: "Deploy using Docker and docker-compose"
inputs:
  docker-user:
    description: "Docker User"
    required: true
  docker-password:
    description: "Docker Password"
    required: true
  ssh-host:
    description: "The host you would like to deploy to"
    required: true
  ssh-user:
    description: "SSH User"
    required: false
    default: ci
  ssh-private-key:
    description: "SSH Private Key"
    required: true
runs:
  using: "composite"
  steps:
    - id: docker-login
      run: echo ${{ inputs.docker-password }} | docker login https://docker.pkg.github.com --username ${{ inputs.docker-user }} --password-stdin
      shell: bash
    - id: docker-build
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"):latest .
      shell: bash
    - id: docker-push
      run: docker push docker.pkg.github.com/${{ github.repository }}/$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"):latest
      shell: bash
